title: Cathy Spigarelli | EHS Professional | Writer | Mom.
description: Hello, I'm Cathy. Welcome to the home of my thoughts on EHS, work, and happiness.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cathyspigarelli.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Cathy Spigarelli # add your name
author-img: about.jpg # add your photo
about-author: I am an Environment, Health, and Safety manager with a passion for introspection and writing about it. # add description
social-instagram: cathyspigarelli # add your Instagram handle
social-facebook: cathy.spig # add your Facebook handle
social-github:  # add your Github handle
social-linkedin: cathy-spigarelli-21768610 # add your Linkedin handle
social-email: cathy@cathyspigarelli.com # add your Email address

# Disqus
discus-identifier: cathyspigarelli # add your discus identifier

# Tracker
analytics: UA-163796508-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
